window.PETS_ARCHIVE = {
  artist: {
    name: "曾沛慈",
    english: "Pets Tseng",
    born: "1984-10-21",
    bornPlace: "中国台北",
    roles: ["歌手", "演员", "主持人"],
    tagline: "谢谢生命中遇见的每一份礼物。",
    bio: "2008 年以《超级星光大道》第六名出道，后以《终极三国》孙尚香、《终极一班》雷婷走进大众视野。2013 年《一个人想着一个人》成为一代青春记忆；2014 年起陆续发行《我是曾沛慈 I'm Pets》《我爱你 以上》《谜之音》《今天阳光就是特别耀眼特别和谐》《下周同样时间》。2019 年凭《我们与恶的距离》应思悦获金钟奖戏剧节目女配角。2026 年于《乘风2026》夺下年度总冠军，并官宣 2027《礼物》世界巡回演唱会。",
  },
  voices: [
    {
      id: "wave-one",
      title: "一个人想着一个人",
      year: 2026,
      note: "初舞台",
      bvid: "BV1nuDgBREJE",
      list: "浪姐",
    },
    {
      id: "wave-half",
      title: "一半一半",
      year: 2026,
      note: "一公 · 与淡淡、黄灿灿",
      bvid: "BV1rqQcBqEmk",
      list: "浪姐",
    },
    {
      id: "wave-chapter",
      title: "篇章",
      year: 2026,
      note: "二公 · 与王濛、黄灿灿",
      bvid: "BV1hio9B2EvU",
      list: "浪姐",
    },
    {
      id: "wave-words",
      title: "言不由衷",
      year: 2026,
      note: "二公 · 与张月",
      bvid: "BV1SgZFBfE95",
      list: "浪姐",
    },
    {
      id: "wave-first-love",
      title: "第一次爱的人",
      year: 2026,
      note: "三公 · 与谢楠、万千惠、张慧雯、徐梦洁",
      bvid: "BV1tZGe6yEnZ",
      list: "浪姐",
    },
    {
      id: "wave-moon",
      title: "一样的月光",
      year: 2026,
      note: "三公 · 队长独奏",
      bvid: "BV1xaG76tEBt",
      list: "浪姐",
    },
    {
      id: "wave-baolian",
      title: "宝莲",
      year: 2026,
      note: "三公帮唱 · 与徐梦洁、孟佳、王霏霏",
      bvid: "BV1z5GH6xExR",
      list: "浪姐",
    },
    {
      id: "wave-susan",
      title: "Susan说",
      year: 2026,
      note: "四公 · 与谢楠、叶一茜、陈瑶、黄灿灿",
      bvid: "BV1Ub7D6TEjd",
      list: "浪姐",
    },
    {
      id: "wave-geqian",
      title: "搁浅",
      year: 2026,
      note: "四公 · 与叶一茜",
      bvid: "BV1owEu6qEqT",
      list: "浪姐",
    },
    {
      id: "wave-gravity",
      title: "心引力",
      year: 2026,
      note: "五公 · 与范玮琪、唐艺昕、庄法、徐梦洁",
      bvid: "BV1Chj66wEmX",
      list: "浪姐",
    },
    {
      id: "wave-how",
      title: "怎么说我不爱你",
      year: 2026,
      note: "五公 · 与庄法",
      bvid: "BV1usjH6WEoz",
      list: "浪姐",
    },
    {
      id: "wave-knockout",
      title: "KNOCKOUT",
      year: 2026,
      note: "乘风之夜 · 与李心洁、淡淡、阚清子、庄法、安崎",
      bvid: "BV1Bn7s62ExZ",
      list: "浪姐",
    },
    {
      id: "cloud",
      title: "会开花的云",
      year: 2026,
      note: "乘风之夜 · 与李心洁",
      bvid: "BV12w7s6fEih",
      list: "浪姐",
    },
    {
      id: "after-everything",
      title: "After Everything",
      year: 2026,
      note: "《来！金来号！》插曲 · 录音棚完整版",
      bvid: "BV1beec6BEse",
      list: "个人",
      autoplay: true,
    },
    {
      id: "count-ten",
      title: "数到十",
      year: 2025,
      note: "《下周同样时间》主打",
      bvid: "BV1a9h969Ez5",
      list: "个人",
    },
    {
      id: "stay-tuned",
      title: "下周同样时间",
      year: 2025,
      note: "第五张专辑同名曲",
      bvid: "BV1D1jizLEsv",
      list: "个人",
    },
    {
      id: "what-love",
      title: "关于爱这件事",
      year: 2025,
      note: "官方现场",
      bvid: "BV1w7SYB9EmC",
      list: "个人",
    },
    {
      id: "sunlight",
      title: "今天阳光就是特别耀眼特别和谐 feat. 韦礼安",
      year: 2022,
      note: "第四张专辑同名曲",
      bvid: "BV1UR4y1Z7FK",
      list: "个人",
    },
    {
      id: "only-you",
      title: "只在意你的一切",
      year: 2022,
      note: "第四张专辑",
      bvid: "BV1rP411V7nM",
      list: "个人",
    },
    {
      id: "wakeful",
      title: "失眠的人",
      year: 2022,
      note: "官方 MV",
      bvid: "BV1iqgkzWEWw",
      list: "个人",
    },
    {
      id: "generous",
      title: "慷慨",
      year: 2022,
      note: "官方 MV",
      bvid: "BV1MG4y1i7KK",
      list: "个人",
    },
    {
      id: "confession",
      title: "谜之音",
      year: 2019,
      note: "第三张专辑同名曲",
      bvid: "BV1wt411P7Vm",
      list: "个人",
    },
    {
      id: "miss-you",
      title: "大风吹",
      year: 2019,
      note: "《谜之音》",
      bvid: "BV1LJ411N7Ne",
      list: "个人",
    },
    {
      id: "how-could-you",
      title: "怎么能这样",
      year: 2019,
      note: "《谜之音》",
      bvid: "BV1n4411U7tZ",
      list: "个人",
    },
    {
      id: "nothing",
      title: "没什么不能爱",
      year: 2018,
      note: "单曲",
      bvid: "BV1zE411f7AB",
      list: "个人",
    },
    {
      id: "favor",
      title: "偏爱",
      year: 2017,
      note: "《我爱你 以上》",
      bvid: "BV1HsovBGEgz",
      list: "个人",
    },
    {
      id: "i-love-you",
      title: "我爱你",
      year: 2017,
      note: "《我爱你 以上》",
      bvid: "BV138SSBSEHm",
      list: "个人",
    },
    {
      id: "not-the-one",
      title: "我不是你该爱的那个人",
      year: 2016,
      note: "《终极一班4》片尾曲",
      bvid: "BV1ys411k7aZ",
      list: "个人",
    },
    {
      id: "a-little",
      title: "不过失去了一点点",
      year: 2014,
      note: "首张专辑主打",
      bvid: "BV15x411e7Sz",
      list: "个人",
    },
    {
      id: "years-later",
      title: "多年后",
      year: 2014,
      note: "《我是曾沛慈 I'm Pets》",
      bvid: "BV1FgoiBrEK1",
      list: "个人",
    },
    {
      id: "glasses",
      title: "黑框眼镜",
      year: 2014,
      note: "《我是曾沛慈 I'm Pets》",
      bvid: "BV1AAoiBjEaS",
      list: "个人",
    },
    {
      id: "still-thinking",
      title: "一个人还是想着一个人",
      year: 2015,
      note: "《终极一班3》片尾曲",
      bvid: "BV1Va411d7iW",
      list: "个人",
    },
    {
      id: "one-person",
      title: "一个人想着一个人",
      year: 2013,
      note: "《终极一班2》片尾曲",
      bvid: "BV1j7411Y7nG",
      list: "个人",
    },
    {
      id: "enough-love",
      title: "够爱",
      year: 2011,
      note: "早期单曲 · 录音棚版",
      bvid: "BV1pt421b7AP",
      list: "个人",
    },
    {
      id: "tears",
      title: "泪了",
      year: 2009,
      note: "《终极三国》",
      bvid: "BV16m4y1D7os",
      list: "个人",
    },
  ],
  quotes: [
    {
      id: "q-gift",
      text: "谢谢生命中遇见的每一份礼物。",
      source: "华研国际／《礼物》世界巡回演唱会官宣",
      year: 2026,
      tags: ["巡演", "礼物"],
    },
    {
      id: "q-arena",
      text: "我是曾沛慈，我一直都很喜欢唱歌，但这次，我可以在体育馆唱歌给你们听了，喔耶！",
      source: "曾沛慈微博，官宣《礼物》巡演",
      year: 2026,
      tags: ["巡演", "心愿"],
    },
    {
      id: "q-wish",
      text: "站在很大的舞台唱歌是我很久之前在内心默默许下的愿望，随着时间过去，我渐渐放下这个目标，久到我几乎忘记这个愿望。不是它不重要，是我知道我不再需要为了证明自己而唱，只要能唱歌，其实在什么舞台唱我都会一样认真面对。",
      source: "曾沛慈微博，官宣《礼物》巡演",
      year: 2026,
      tags: ["舞台", "初心"],
    },
    {
      id: "q-waited",
      text: "开万人演唱会是自己一直以来的愿望，但时间久到我都快忘记这个愿望了，今天看到官宣的时候就想，我真的等到这一天了。",
      source: "《礼物》巡演北京发布会",
      year: 2026,
      tags: ["巡演", "发布会"],
    },
    {
      id: "q-im-pets",
      text: "我是曾沛慈。我热爱歌唱，我勇敢踏上我的音乐路。",
      source: "首张专辑《我是曾沛慈 I'm Pets》宣传",
      year: 2014,
      tags: ["专辑", "出道"],
    },
    {
      id: "q-second",
      text: "就算成为你第一名的好朋友，却永远只是第二名的情人。",
      source: "《我是曾沛慈 I'm Pets》专辑前导预告",
      year: 2014,
      tags: ["专辑"],
    },
    {
      id: "q-ticc-nervous",
      text: "这场演唱会我真的很紧张，因为是我很看重、很在乎的演出，所以对自己要求特别高，我每天都练唱到半夜，希望可以给你们看到最好的一面。",
      source: "《谜之音》演唱会，台北国际会议中心",
      year: 2019,
      tags: ["演唱会", "谜之音"],
    },
    {
      id: "q-tight",
      text: "这应该是我有史以来穿最贴身的一次，超级贴。",
      source: "《谜之音》演唱会开场",
      year: 2019,
      tags: ["演唱会", "现场"],
    },
    {
      id: "q-infinite",
      text: "礼物是有形的载体，但承载的陪伴与热爱是无限的。「圆」象征着团圆与奔赴，演唱会是她与歌迷跨越山海、温暖相聚的盛大时刻。",
      source: "《礼物》巡演发布会舞美概念（转述）",
      year: 2026,
      tags: ["巡演", "舞美"],
    },
    {
      id: "q-chengfeng-intro",
      text: "今晚我把《一个人想着一个人》唱给你听。",
      source: "《乘风2026》初舞台前动态",
      year: 2026,
      tags: ["乘风2026"],
    },
  ],
  stages: [
    { id: "s-xg-01", date: "2007", place: "超级星光大道", venue: "电视舞台", title: "梦一场", note: "百人淘汰赛 · 15 分", kind: "星光" },
    { id: "s-xg-03", date: "2007", place: "超级星光大道", venue: "电视舞台", title: "没有人", note: "音乐故事指定赛 · 19 分", kind: "星光" },
    { id: "s-xg-11", date: "2007", place: "超级星光大道", venue: "电视舞台", title: "傻瓜（温岚）", note: "新歌指定曲 · 24 分，黑马之姿", kind: "星光" },
    { id: "s-xg-12", date: "2007", place: "超级星光大道", venue: "电视舞台", title: "没有烟抽的日子", note: "23 分，赢得电影主题曲《唱出希望》", kind: "星光" },
    { id: "s-xg-13", date: "2007", place: "超级星光大道", venue: "电视舞台", title: "Cappuccino", note: "快歌指定曲 · 24 分", kind: "星光" },
    { id: "s-xg-22", date: "2007", place: "超级星光大道", venue: "电视舞台", title: "火柴天堂", note: "一比一 PK · 胜", kind: "星光" },
    { id: "s-xg-26", date: "2008", place: "超级星光大道", venue: "电视舞台", title: "温柔的慈悲／马德里不思议", note: "第六名决定赛", kind: "星光" },
    { id: "c-2010-0424", date: "2010-04-24", place: "台北", venue: "河岸留言西门红楼", title: "我是「曾沛慈」演唱会", note: "首场个人演唱会，完售", kind: "演唱会" },
    { id: "c-2010-0820", date: "2010-08-20", place: "台北", venue: "河岸留言西门红楼", title: "听说·曾沛慈 演唱会", note: "开票数小时完售", kind: "演唱会" },
    { id: "c-2010-1008", date: "2010-10-08", place: "香港", venue: "协青社蒲吧", title: "曾沛慈香港初登场演唱会", note: "与东城卫", kind: "演唱会" },
    { id: "c-2011-0521", date: "2011-05-21", place: "台北", venue: "河岸留言西门红楼", title: ">100° 幸福曾沛慈演唱会", note: "", kind: "演唱会" },
    { id: "c-2011-1022", date: "2011-10-22", place: "台北", venue: "河岸留言西门红楼", title: "出发吧！曾沛慈演唱会", note: "自创曲《可爱奇怪》", kind: "演唱会" },
    { id: "c-2013-0215", date: "2013-02-15", place: "台北", venue: "Legacy Taipei", title: "开。房间 演唱会（加场）", note: "开票 30 分钟完售", kind: "演唱会" },
    { id: "c-2013-0216", date: "2013-02-16", place: "台北", venue: "Legacy Taipei", title: "开。房间 演唱会", note: "汪东城、SpeXial 嘉宾", kind: "演唱会" },
    { id: "c-2015-0207", date: "2015-02-07", place: "台北", venue: "Legacy Taipei", title: "2015 我是曾沛慈 Live Concert", note: "开票 8 分钟完售", kind: "演唱会" },
    { id: "c-2015-0208", date: "2015-02-08", place: "台北", venue: "Legacy Taipei", title: "2015 我是曾沛慈 Live Concert 加场", note: "完售", kind: "演唱会" },
    { id: "c-2015-0228", date: "2015-02-28", place: "新加坡", venue: "Shanghai Dolly", title: "我是曾沛慈 I'm Pets 音乐会", note: "首场新加坡音乐会，即日完售", kind: "演唱会" },
    { id: "c-2015-0501", date: "2015-05-01", place: "北京", venue: "糖果 TANGO", title: "我是曾沛慈 Live Concert 北京站", note: "完售", kind: "演唱会" },
    { id: "c-2015-0516", date: "2015-05-16", place: "广州", venue: "中央车站 Rock House", title: "我是曾沛慈 Live Concert 广州站", note: "完售", kind: "演唱会" },
    { id: "c-2015-0821", date: "2015-08-21", place: "上海", venue: "浅水湾文化中心", title: "我是曾沛慈 Live Concert 上海站", note: "", kind: "演唱会" },
    { id: "c-2017-0805", date: "2017-08-05", place: "台北", venue: "台北国际会议中心", title: "我爱你 演唱会", note: "首场大型售票演唱会，开票 10 分钟完售", kind: "演唱会" },
    { id: "c-2017-1015", date: "2017-10-15", place: "吉隆坡", venue: "Mega Star Arena", title: "我爱你 演唱会 大马站", note: "首场马来西亚巡演", kind: "演唱会" },
    { id: "c-2018-1007", date: "2018-10-07", place: "台北", venue: "Legacy Taipei", title: "致亲爱的 演唱会", note: "开票 10 分钟完售", kind: "演唱会" },
    { id: "c-2018-1012", date: "2018-10-12", place: "台中", venue: "Legacy Taichung", title: "致亲爱的 演唱会", note: "", kind: "演唱会" },
    { id: "c-2019-1122", date: "2019-11-22", place: "台北", venue: "台北国际会议中心", title: "谜之音 演唱会", note: "连唱 25 首；嘉宾魏如萱；安可《这里还有我》", kind: "演唱会" },
    { id: "c-2022-1106", date: "2022-11-06", place: "台北", venue: "Legacy Taipei", title: "今天阳光就是特别耀眼特别和谐演唱会", note: "开票 10 分钟完售", kind: "演唱会" },
    { id: "c-2023-1013", date: "2023-10-13", place: "新加坡", venue: "Capitol Theatre", title: "This is Live! Chill Hi 嗨音乐趴", note: "首场新加坡演唱会", kind: "演唱会" },
    { id: "c-2024-1220", date: "2024-12-20", place: "上海", venue: "蜚声上海 Live House", title: "曾经，以后 巡回音乐会", note: "", kind: "演唱会" },
    { id: "c-2024-1227", date: "2024-12-27", place: "杭州", venue: "杭州 SoFun Live", title: "曾经，以后 巡回音乐会", note: "", kind: "演唱会" },
    { id: "c-2025-0110", date: "2025-01-10", place: "广州", venue: "MAO Livehouse 广州", title: "曾经，以后 巡回音乐会", note: "", kind: "演唱会" },
    { id: "c-2025-0111", date: "2025-01-11", place: "广州", venue: "MAO Livehouse 广州", title: "曾经，以后 巡回音乐会 加场", note: "", kind: "演唱会" },
    { id: "c-2025-0322", date: "2025-03-22", place: "成都", venue: "CH8 绿树演艺中心", title: "曾经，以后 巡回音乐会", note: "", kind: "演唱会" },
    { id: "c-2025-0411", date: "2025-04-11", place: "深圳", venue: "SoFun Live 深圳", title: "曾经，以后 巡回音乐会 加场", note: "", kind: "演唱会" },
    { id: "c-2025-0412", date: "2025-04-12", place: "深圳", venue: "SoFun Live 深圳", title: "曾经，以后 巡回音乐会", note: "", kind: "演唱会" },
    { id: "c-2025-0426", date: "2025-04-26", place: "南京", venue: "稻香演艺中心", title: "曾经，以后 巡回音乐会", note: "", kind: "演唱会" },
    { id: "c-2025-0628", date: "2025-06-28", place: "北京", venue: "北京蛙厂 RMMF·798", title: "曾经，以后 巡回音乐会", note: "", kind: "演唱会" },
    { id: "c-2025-1108", date: "2025-11-08", place: "台北", venue: "台北流行音乐中心", title: "关于爱这件事 巡回演唱会", note: "首次约 5000 人场个人演唱会", kind: "演唱会" },
    { id: "cf-0", date: "2026", place: "乘风2026", venue: "初舞台", title: "一个人想着一个人", note: "对决淡淡 · 乘风值 483 · 晋级", kind: "乘风2026", voiceId: "wave-one" },
    { id: "cf-1", date: "2026", place: "乘风2026", venue: "第一场公演", title: "一半一半", note: "队长团秀 · 安全 · 个人喜爱度第 5", kind: "乘风2026", voiceId: "wave-half" },
    { id: "cf-2a", date: "2026", place: "乘风2026", venue: "第二场公演", title: "篇章", note: "团秀 · 安全", kind: "乘风2026", voiceId: "wave-chapter" },
    { id: "cf-2b", date: "2026", place: "乘风2026", venue: "第二场公演", title: "言不由衷", note: "能力者对决张月", kind: "乘风2026", voiceId: "wave-words" },
    { id: "cf-3a", date: "2026", place: "乘风2026", venue: "第三场公演", title: "第一次爱的人", note: "六团团秀队长 · 喜爱度第 2", kind: "乘风2026", voiceId: "wave-first-love" },
    { id: "cf-3b", date: "2026", place: "乘风2026", venue: "第三场公演", title: "一样的月光", note: "队长 Solo 秀", kind: "乘风2026", voiceId: "wave-moon" },
    { id: "cf-3c", date: "2026", place: "乘风2026", venue: "第三场公演", title: "宝莲", note: "师姐帮帮唱", kind: "乘风2026", voiceId: "wave-baolian" },
    { id: "cf-4a", date: "2026", place: "乘风2026", venue: "第四场公演", title: "Susan说", note: "六团团秀队长 · 喜爱度第 1", kind: "乘风2026", voiceId: "wave-susan" },
    { id: "cf-4b", date: "2026", place: "乘风2026", venue: "第四场公演", title: "搁浅", note: "团内双人合作叶一茜", kind: "乘风2026", voiceId: "wave-geqian" },
    { id: "cf-5a", date: "2026", place: "乘风2026", venue: "第五场公演", title: "心引力", note: "五团团秀队长 · 喜爱度第 1", kind: "乘风2026", voiceId: "wave-gravity" },
    { id: "cf-5b", date: "2026", place: "乘风2026", venue: "第五场公演", title: "怎么说我不爱你", note: "团内双人合作庄法", kind: "乘风2026", voiceId: "wave-how" },
    { id: "cf-f1", date: "2026-06-27", place: "乘风2026", venue: "乘风之夜", title: "KNOCKOUT", note: "四团团秀队长 · 年度总冠军", kind: "乘风2026", voiceId: "wave-knockout" },
    { id: "cf-f2", date: "2026-06-27", place: "乘风2026", venue: "乘风之夜", title: "会开花的云", note: "与李心洁 · 可在本站聆听", kind: "乘风2026", voiceId: "cloud" },
    { id: "gift-cs", date: "2027-01-09", place: "长沙", venue: "湖南国际会展中心芒果馆", title: "礼物 世界巡回演唱会", note: "已公布日期；其余城市待官宣", kind: "礼物巡演" },
    { id: "gift-sz", date: "2027-05-15", place: "深圳", venue: "深圳湾体育中心体育馆", title: "礼物 世界巡回演唱会", note: "已公布日期", kind: "礼物巡演" },
    { id: "gift-gz", date: "2027", place: "广州", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
    { id: "gift-sh", date: "2027", place: "上海", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
    { id: "gift-hz", date: "2027", place: "杭州", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
    { id: "gift-bj", date: "2027", place: "北京", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
    { id: "gift-xm", date: "2027", place: "厦门", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
    { id: "gift-wh", date: "2027", place: "武汉", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
    { id: "gift-cd", date: "2027", place: "成都", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
    { id: "gift-su", date: "2027", place: "苏州", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
    { id: "gift-kl", date: "2027", place: "吉隆坡", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
    { id: "gift-sg", date: "2027", place: "新加坡", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
    { id: "gift-tp", date: "2027", place: "台北", venue: "待公布", title: "礼物 世界巡回演唱会", note: "官宣城市", kind: "礼物巡演" },
  ],
  albums: [
    { year: 2014, title: "我是曾沛慈 I'm Pets", label: "福茂唱片", hits: ["不过失去了一点点", "多年后", "一个人还是想着一个人"] },
    { year: 2017, title: "我爱你 以上", label: "福茂唱片", hits: ["偏爱", "我不是你该爱的那个人", "我爱你"] },
    { year: 2019, title: "谜之音", label: "亚神音乐", hits: ["谜之音", "怎么能这样", "大风吹"] },
    { year: 2022, title: "今天阳光就是特别耀眼特别和谐", label: "亚神音乐", hits: ["今天阳光就是特别耀眼特别和谐", "只在意你的一切"] },
    { year: 2025, title: "下周同样时间", label: "华研国际音乐", hits: ["数到十", "下周同样时间", "关于爱这件事"] },
  ],
};
