SET NAMES utf8mb4;

INSERT INTO artist (id, name, english_name, born, born_place, roles, tagline, bio) VALUES (1, '曾沛慈', 'Pets Tseng', '1984-10-21', '中国台北', '歌手 / 演员 / 主持人', '谢谢生命中遇见的每一份礼物。', '2008 年以《超级星光大道》第六名出道，后以《终极三国》孙尚香、《终极一班》雷婷走进大众视野。2013 年《一个人想着一个人》成为一代青春记忆；2014 年起陆续发行《我是曾沛慈 I''m Pets》《我爱你 以上》《谜之音》《今天阳光就是特别耀眼特别和谐》《下周同样时间》。2019 年凭《我们与恶的距离》应思悦获金钟奖戏剧节目女配角。2026 年于《乘风2026》夺下年度总冠军，并官宣 2027《礼物》世界巡回演唱会。');

INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-one', '一个人想着一个人', 2026, '初舞台', 'BV1nuDgBREJE', '浪姐', 0, 0);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-half', '一半一半', 2026, '一公 · 与淡淡、黄灿灿', 'BV1rqQcBqEmk', '浪姐', 0, 1);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-chapter', '篇章', 2026, '二公 · 与王濛、黄灿灿', 'BV1hio9B2EvU', '浪姐', 0, 2);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-words', '言不由衷', 2026, '二公 · 与张月', 'BV1SgZFBfE95', '浪姐', 0, 3);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-first-love', '第一次爱的人', 2026, '三公 · 与谢楠、万千惠、张慧雯、徐梦洁', 'BV1tZGe6yEnZ', '浪姐', 0, 4);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-moon', '一样的月光', 2026, '三公 · 队长独奏', 'BV1xaG76tEBt', '浪姐', 0, 5);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-baolian', '宝莲', 2026, '三公帮唱 · 与徐梦洁、孟佳、王霏霏', 'BV1z5GH6xExR', '浪姐', 0, 6);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-susan', 'Susan说', 2026, '四公 · 与谢楠、叶一茜、陈瑶、黄灿灿', 'BV1Ub7D6TEjd', '浪姐', 0, 7);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-geqian', '搁浅', 2026, '四公 · 与叶一茜', 'BV1owEu6qEqT', '浪姐', 0, 8);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-gravity', '心引力', 2026, '五公 · 与范玮琪、唐艺昕、庄法、徐梦洁', 'BV1Chj66wEmX', '浪姐', 0, 9);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-how', '怎么说我不爱你', 2026, '五公 · 与庄法', 'BV1usjH6WEoz', '浪姐', 0, 10);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wave-knockout', 'KNOCKOUT', 2026, '乘风之夜 · 与李心洁、淡淡、阚清子、庄法、安崎', 'BV1Bn7s62ExZ', '浪姐', 0, 11);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('cloud', '会开花的云', 2026, '乘风之夜 · 与李心洁', 'BV12w7s6fEih', '浪姐', 0, 12);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('after-everything', 'After Everything', 2026, '《来！金来号！》插曲 · 录音棚完整版', 'BV1beec6BEse', '个人', 1, 13);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('count-ten', '数到十', 2025, '《下周同样时间》主打', 'BV1a9h969Ez5', '个人', 0, 14);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('stay-tuned', '下周同样时间', 2025, '第五张专辑同名曲', 'BV1D1jizLEsv', '个人', 0, 15);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('what-love', '关于爱这件事', 2025, '官方现场', 'BV1w7SYB9EmC', '个人', 0, 16);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('sunlight', '今天阳光就是特别耀眼特别和谐 feat. 韦礼安', 2022, '第四张专辑同名曲', 'BV1UR4y1Z7FK', '个人', 0, 17);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('only-you', '只在意你的一切', 2022, '第四张专辑', 'BV1rP411V7nM', '个人', 0, 18);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('wakeful', '失眠的人', 2022, '官方 MV', 'BV1iqgkzWEWw', '个人', 0, 19);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('generous', '慷慨', 2022, '官方 MV', 'BV1MG4y1i7KK', '个人', 0, 20);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('confession', '谜之音', 2019, '第三张专辑同名曲', 'BV1wt411P7Vm', '个人', 0, 21);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('miss-you', '大风吹', 2019, '《谜之音》', 'BV1LJ411N7Ne', '个人', 0, 22);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('how-could-you', '怎么能这样', 2019, '《谜之音》', 'BV1n4411U7tZ', '个人', 0, 23);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('nothing', '没什么不能爱', 2018, '单曲', 'BV1zE411f7AB', '个人', 0, 24);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('favor', '偏爱', 2017, '《我爱你 以上》', 'BV1HsovBGEgz', '个人', 0, 25);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('i-love-you', '我爱你', 2017, '《我爱你 以上》', 'BV138SSBSEHm', '个人', 0, 26);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('not-the-one', '我不是你该爱的那个人', 2016, '《终极一班4》片尾曲', 'BV1ys411k7aZ', '个人', 0, 27);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('a-little', '不过失去了一点点', 2014, '首张专辑主打', 'BV15x411e7Sz', '个人', 0, 28);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('years-later', '多年后', 2014, '《我是曾沛慈 I''m Pets》', 'BV1FgoiBrEK1', '个人', 0, 29);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('glasses', '黑框眼镜', 2014, '《我是曾沛慈 I''m Pets》', 'BV1AAoiBjEaS', '个人', 0, 30);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('still-thinking', '一个人还是想着一个人', 2015, '《终极一班3》片尾曲', 'BV1Va411d7iW', '个人', 0, 31);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('one-person', '一个人想着一个人', 2013, '《终极一班2》片尾曲', 'BV1j7411Y7nG', '个人', 0, 32);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('enough-love', '够爱', 2011, '早期单曲 · 录音棚版', 'BV1pt421b7AP', '个人', 0, 33);
INSERT INTO voice (id, title, release_year, note, bvid, list_name, autoplay, sort_no) VALUES ('tears', '泪了', 2009, '《终极三国》', 'BV16m4y1D7os', '个人', 0, 34);

INSERT INTO quote_item (id, content, origin, quote_year, sort_no) VALUES ('q-gift', '谢谢生命中遇见的每一份礼物。', '华研国际／《礼物》世界巡回演唱会官宣', 2026, 0);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-gift', '巡演', 0);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-gift', '礼物', 1);
INSERT INTO quote_item (id, content, origin, quote_year, sort_no) VALUES ('q-arena', '我是曾沛慈，我一直都很喜欢唱歌，但这次，我可以在体育馆唱歌给你们听了，喔耶！', '曾沛慈微博，官宣《礼物》巡演', 2026, 1);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-arena', '巡演', 0);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-arena', '心愿', 1);
INSERT INTO quote_item (id, content, origin, quote_year, sort_no) VALUES ('q-wish', '站在很大的舞台唱歌是我很久之前在内心默默许下的愿望，随着时间过去，我渐渐放下这个目标，久到我几乎忘记这个愿望。不是它不重要，是我知道我不再需要为了证明自己而唱，只要能唱歌，其实在什么舞台唱我都会一样认真面对。', '曾沛慈微博，官宣《礼物》巡演', 2026, 2);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-wish', '舞台', 0);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-wish', '初心', 1);
INSERT INTO quote_item (id, content, origin, quote_year, sort_no) VALUES ('q-waited', '开万人演唱会是自己一直以来的愿望，但时间久到我都快忘记这个愿望了，今天看到官宣的时候就想，我真的等到这一天了。', '《礼物》巡演北京发布会', 2026, 3);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-waited', '巡演', 0);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-waited', '发布会', 1);
INSERT INTO quote_item (id, content, origin, quote_year, sort_no) VALUES ('q-im-pets', '我是曾沛慈。我热爱歌唱，我勇敢踏上我的音乐路。', '首张专辑《我是曾沛慈 I''m Pets》宣传', 2014, 4);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-im-pets', '专辑', 0);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-im-pets', '出道', 1);
INSERT INTO quote_item (id, content, origin, quote_year, sort_no) VALUES ('q-second', '就算成为你第一名的好朋友，却永远只是第二名的情人。', '《我是曾沛慈 I''m Pets》专辑前导预告', 2014, 5);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-second', '专辑', 0);
INSERT INTO quote_item (id, content, origin, quote_year, sort_no) VALUES ('q-ticc-nervous', '这场演唱会我真的很紧张，因为是我很看重、很在乎的演出，所以对自己要求特别高，我每天都练唱到半夜，希望可以给你们看到最好的一面。', '《谜之音》演唱会，台北国际会议中心', 2019, 6);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-ticc-nervous', '演唱会', 0);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-ticc-nervous', '谜之音', 1);
INSERT INTO quote_item (id, content, origin, quote_year, sort_no) VALUES ('q-tight', '这应该是我有史以来穿最贴身的一次，超级贴。', '《谜之音》演唱会开场', 2019, 7);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-tight', '演唱会', 0);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-tight', '现场', 1);
INSERT INTO quote_item (id, content, origin, quote_year, sort_no) VALUES ('q-infinite', '礼物是有形的载体，但承载的陪伴与热爱是无限的。「圆」象征着团圆与奔赴，演唱会是她与歌迷跨越山海、温暖相聚的盛大时刻。', '《礼物》巡演发布会舞美概念（转述）', 2026, 8);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-infinite', '巡演', 0);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-infinite', '舞美', 1);
INSERT INTO quote_item (id, content, origin, quote_year, sort_no) VALUES ('q-chengfeng-intro', '今晚我把《一个人想着一个人》唱给你听。', '《乘风2026》初舞台前动态', 2026, 9);
INSERT INTO quote_tag (quote_id, tag, sort_no) VALUES ('q-chengfeng-intro', '乘风2026', 0);

INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('s-xg-01', '2007', '超级星光大道', '电视舞台', '梦一场', '百人淘汰赛 · 15 分', '星光', NULL, 0);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('s-xg-03', '2007', '超级星光大道', '电视舞台', '没有人', '音乐故事指定赛 · 19 分', '星光', NULL, 1);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('s-xg-11', '2007', '超级星光大道', '电视舞台', '傻瓜（温岚）', '新歌指定曲 · 24 分，黑马之姿', '星光', NULL, 2);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('s-xg-12', '2007', '超级星光大道', '电视舞台', '没有烟抽的日子', '23 分，赢得电影主题曲《唱出希望》', '星光', NULL, 3);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('s-xg-13', '2007', '超级星光大道', '电视舞台', 'Cappuccino', '快歌指定曲 · 24 分', '星光', NULL, 4);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('s-xg-22', '2007', '超级星光大道', '电视舞台', '火柴天堂', '一比一 PK · 胜', '星光', NULL, 5);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('s-xg-26', '2008', '超级星光大道', '电视舞台', '温柔的慈悲／马德里不思议', '第六名决定赛', '星光', NULL, 6);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2010-0424', '2010-04-24', '台北', '河岸留言西门红楼', '我是「曾沛慈」演唱会', '首场个人演唱会，完售', '演唱会', NULL, 7);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2010-0820', '2010-08-20', '台北', '河岸留言西门红楼', '听说·曾沛慈 演唱会', '开票数小时完售', '演唱会', NULL, 8);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2010-1008', '2010-10-08', '香港', '协青社蒲吧', '曾沛慈香港初登场演唱会', '与东城卫', '演唱会', NULL, 9);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2011-0521', '2011-05-21', '台北', '河岸留言西门红楼', '>100° 幸福曾沛慈演唱会', '', '演唱会', NULL, 10);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2011-1022', '2011-10-22', '台北', '河岸留言西门红楼', '出发吧！曾沛慈演唱会', '自创曲《可爱奇怪》', '演唱会', NULL, 11);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2013-0215', '2013-02-15', '台北', 'Legacy Taipei', '开。房间 演唱会（加场）', '开票 30 分钟完售', '演唱会', NULL, 12);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2013-0216', '2013-02-16', '台北', 'Legacy Taipei', '开。房间 演唱会', '汪东城、SpeXial 嘉宾', '演唱会', NULL, 13);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2015-0207', '2015-02-07', '台北', 'Legacy Taipei', '2015 我是曾沛慈 Live Concert', '开票 8 分钟完售', '演唱会', NULL, 14);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2015-0208', '2015-02-08', '台北', 'Legacy Taipei', '2015 我是曾沛慈 Live Concert 加场', '完售', '演唱会', NULL, 15);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2015-0228', '2015-02-28', '新加坡', 'Shanghai Dolly', '我是曾沛慈 I''m Pets 音乐会', '首场新加坡音乐会，即日完售', '演唱会', NULL, 16);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2015-0501', '2015-05-01', '北京', '糖果 TANGO', '我是曾沛慈 Live Concert 北京站', '完售', '演唱会', NULL, 17);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2015-0516', '2015-05-16', '广州', '中央车站 Rock House', '我是曾沛慈 Live Concert 广州站', '完售', '演唱会', NULL, 18);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2015-0821', '2015-08-21', '上海', '浅水湾文化中心', '我是曾沛慈 Live Concert 上海站', '', '演唱会', NULL, 19);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2017-0805', '2017-08-05', '台北', '台北国际会议中心', '我爱你 演唱会', '首场大型售票演唱会，开票 10 分钟完售', '演唱会', NULL, 20);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2017-1015', '2017-10-15', '吉隆坡', 'Mega Star Arena', '我爱你 演唱会 大马站', '首场马来西亚巡演', '演唱会', NULL, 21);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2018-1007', '2018-10-07', '台北', 'Legacy Taipei', '致亲爱的 演唱会', '开票 10 分钟完售', '演唱会', NULL, 22);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2018-1012', '2018-10-12', '台中', 'Legacy Taichung', '致亲爱的 演唱会', '', '演唱会', NULL, 23);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2019-1122', '2019-11-22', '台北', '台北国际会议中心', '谜之音 演唱会', '连唱 25 首；嘉宾魏如萱；安可《这里还有我》', '演唱会', NULL, 24);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2022-1106', '2022-11-06', '台北', 'Legacy Taipei', '今天阳光就是特别耀眼特别和谐演唱会', '开票 10 分钟完售', '演唱会', NULL, 25);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2023-1013', '2023-10-13', '新加坡', 'Capitol Theatre', 'This is Live! Chill Hi 嗨音乐趴', '首场新加坡演唱会', '演唱会', NULL, 26);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2024-1220', '2024-12-20', '上海', '蜚声上海 Live House', '曾经，以后 巡回音乐会', '', '演唱会', NULL, 27);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2024-1227', '2024-12-27', '杭州', '杭州 SoFun Live', '曾经，以后 巡回音乐会', '', '演唱会', NULL, 28);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2025-0110', '2025-01-10', '广州', 'MAO Livehouse 广州', '曾经，以后 巡回音乐会', '', '演唱会', NULL, 29);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2025-0111', '2025-01-11', '广州', 'MAO Livehouse 广州', '曾经，以后 巡回音乐会 加场', '', '演唱会', NULL, 30);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2025-0322', '2025-03-22', '成都', 'CH8 绿树演艺中心', '曾经，以后 巡回音乐会', '', '演唱会', NULL, 31);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2025-0411', '2025-04-11', '深圳', 'SoFun Live 深圳', '曾经，以后 巡回音乐会 加场', '', '演唱会', NULL, 32);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2025-0412', '2025-04-12', '深圳', 'SoFun Live 深圳', '曾经，以后 巡回音乐会', '', '演唱会', NULL, 33);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2025-0426', '2025-04-26', '南京', '稻香演艺中心', '曾经，以后 巡回音乐会', '', '演唱会', NULL, 34);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2025-0628', '2025-06-28', '北京', '北京蛙厂 RMMF·798', '曾经，以后 巡回音乐会', '', '演唱会', NULL, 35);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('c-2025-1108', '2025-11-08', '台北', '台北流行音乐中心', '关于爱这件事 巡回演唱会', '首次约 5000 人场个人演唱会', '演唱会', NULL, 36);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-0', '2026', '乘风2026', '初舞台', '一个人想着一个人', '对决淡淡 · 乘风值 483 · 晋级', '乘风2026', 'wave-one', 37);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-1', '2026', '乘风2026', '第一场公演', '一半一半', '队长团秀 · 安全 · 个人喜爱度第 5', '乘风2026', 'wave-half', 38);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-2a', '2026', '乘风2026', '第二场公演', '篇章', '团秀 · 安全', '乘风2026', 'wave-chapter', 39);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-2b', '2026', '乘风2026', '第二场公演', '言不由衷', '能力者对决张月', '乘风2026', 'wave-words', 40);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-3a', '2026', '乘风2026', '第三场公演', '第一次爱的人', '六团团秀队长 · 喜爱度第 2', '乘风2026', 'wave-first-love', 41);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-3b', '2026', '乘风2026', '第三场公演', '一样的月光', '队长 Solo 秀', '乘风2026', 'wave-moon', 42);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-3c', '2026', '乘风2026', '第三场公演', '宝莲', '师姐帮帮唱', '乘风2026', 'wave-baolian', 43);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-4a', '2026', '乘风2026', '第四场公演', 'Susan说', '六团团秀队长 · 喜爱度第 1', '乘风2026', 'wave-susan', 44);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-4b', '2026', '乘风2026', '第四场公演', '搁浅', '团内双人合作叶一茜', '乘风2026', 'wave-geqian', 45);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-5a', '2026', '乘风2026', '第五场公演', '心引力', '五团团秀队长 · 喜爱度第 1', '乘风2026', 'wave-gravity', 46);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-5b', '2026', '乘风2026', '第五场公演', '怎么说我不爱你', '团内双人合作庄法', '乘风2026', 'wave-how', 47);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-f1', '2026-06-27', '乘风2026', '乘风之夜', 'KNOCKOUT', '四团团秀队长 · 年度总冠军', '乘风2026', 'wave-knockout', 48);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('cf-f2', '2026-06-27', '乘风2026', '乘风之夜', '会开花的云', '与李心洁 · 可在本站聆听', '乘风2026', 'cloud', 49);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-cs', '2027-01-09', '长沙', '湖南国际会展中心芒果馆', '礼物 世界巡回演唱会', '已公布日期；其余城市待官宣', '礼物巡演', NULL, 50);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-sz', '2027-05-15', '深圳', '深圳湾体育中心体育馆', '礼物 世界巡回演唱会', '已公布日期', '礼物巡演', NULL, 51);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-gz', '2027', '广州', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 52);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-sh', '2027', '上海', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 53);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-hz', '2027', '杭州', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 54);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-bj', '2027', '北京', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 55);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-xm', '2027', '厦门', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 56);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-wh', '2027', '武汉', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 57);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-cd', '2027', '成都', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 58);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-su', '2027', '苏州', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 59);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-kl', '2027', '吉隆坡', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 60);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-sg', '2027', '新加坡', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 61);
INSERT INTO stage (id, stage_date, place, venue, title, note, kind, voice_id, sort_no) VALUES ('gift-tp', '2027', '台北', '待公布', '礼物 世界巡回演唱会', '官宣城市', '礼物巡演', NULL, 62);

INSERT INTO album (id, release_year, title, label, sort_no) VALUES (1, 2014, '我是曾沛慈 I''m Pets', '福茂唱片', 1);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (1, '不过失去了一点点', 0);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (1, '多年后', 1);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (1, '一个人还是想着一个人', 2);
INSERT INTO album (id, release_year, title, label, sort_no) VALUES (2, 2017, '我爱你 以上', '福茂唱片', 2);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (2, '偏爱', 0);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (2, '我不是你该爱的那个人', 1);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (2, '我爱你', 2);
INSERT INTO album (id, release_year, title, label, sort_no) VALUES (3, 2019, '谜之音', '亚神音乐', 3);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (3, '谜之音', 0);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (3, '怎么能这样', 1);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (3, '大风吹', 2);
INSERT INTO album (id, release_year, title, label, sort_no) VALUES (4, 2022, '今天阳光就是特别耀眼特别和谐', '亚神音乐', 4);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (4, '今天阳光就是特别耀眼特别和谐', 0);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (4, '只在意你的一切', 1);
INSERT INTO album (id, release_year, title, label, sort_no) VALUES (5, 2025, '下周同样时间', '华研国际音乐', 5);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (5, '数到十', 0);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (5, '下周同样时间', 1);
INSERT INTO album_hit (album_id, title, sort_no) VALUES (5, '关于爱这件事', 2);
